# Aljabar Matrik
**Matriks** A adalah larik bilangan 2 dimensi.Komputasi matrik menggunakan numpy , dengan menggunakan array.

-dimensi atau ukuran matrik ditentukan dengan jumlah baris dan kolom .

-jumlah baris dicantumkan terlebih dahulu

-contoh : matriks A (3 x 3),C(2 x 2)

-Matriks yang hanya memiliki 1 kolom, seperti E, biasa disebut vektor.

In [6]:
import numpy as np
A=np.array([[1,2,3],[3,4,5],[9,7,6]])
print(A)
B=np.array([[4,2,4],[3,7,5],[9,7,7]])
C=np.array([[1,2],[3,4],[9,7]])
D=np.array([[1,6,3],[3,7,5],[8,7,9]])
E=np.array([[1,4]])
print(E)

[[1 2 3]
 [3 4 5]
 [9 7 6]]
[[1 4]]


In [ ]:
import numpy as np
B=np.array([[4,2,4],[3,7,5],[9,7,7]])
print(B)

[[4 2 4]
 [3 7 5]
 [9 7 7]]


In [ ]:
import numpy as np
C=np.array([[1,2],[3,4],[9,7]])
print(C.shape)
# saat array sudah dibuat maka dapat diakses juga dengan metode shape
# yang akan memberikan informasi yang pertama jumlah baris dan yang kedua adalah jumlah kolom
print(C)

(3, 2)
[[1 2]
 [3 4]
 [9 7]]


In [ ]:
import numpy as np
D=np.array([[1,6,3],[3,7,5],[8,7,9]])
print(D)

[[1 6 3]
 [3 7 5]
 [8 7 9]]


In [ ]:
E=np.random.randint(10,size=(3,3))
# ini merupakan contoh membuat list dengan nilai array random
print(E)

[[1 9 2]
 [3 9 8]
 [4 9 0]]


In [ ]:
AB1=np.dot(A,B)
print(AB1)

[[ 37  37  35]
 [ 69  69  67]
 [111 109 113]]


### perkalian matriks 3x3.

1. Pertama-tama, kita mengimpor pustaka NumPy dengan pernyataan `import numpy as np`. NumPy adalah pustaka Python yang sangat berguna untuk operasi matriks dan array.

2. Kemudian, kita mendefinisikan dua matriks 3x3, `A` dan `B`, menggunakan fungsi `np.array()`. Anda dapat mengubah nilai elemen matriks sesuai kebutuhan Anda. Dalam contoh ini, `A` memiliki nilai [1,2,3],[3,4,5],[9,7,6]`B` memiliki nilai [4,2,4],[3,7,5],[9,7,7]
3. Selanjutnya, kita menggunakan fungsi `np.dot()` untuk melakukan perkalian matriks antara `A` dan `B`. Fungsi `np.dot()` adalah fungsi bawaan NumPy untuk melakukan perkalian titik antara dua matriks.

4. Hasil perkalian matriks disimpan dalam variabel `AB1`.

5. Akhirnya, kita mencetak hasil perkalian matriks menggunakan pernyataan `print()`.

Dengan menggunakan NumPy, kita dapat dengan mudah melakukan operasi matriks seperti perkalian, penjumlahan, dan operasi matriks lainnya dengan cepat dan efisien dalam Python.

In [ ]:
c=2
d=4
G=(c+A)*A
print(G)

[[ 3  8 15]
 [15 24 35]
 [99 63 48]]


In [ ]:
H=(c*A)+(d*A)
print(H)

[[ 6 12 18]
 [18 24 30]
 [54 42 36]]


In [ ]:
 C.shape

 C.shape[0]


3

In [ ]:
C_T=C.transpose()
print(C_T)

[[1 3 9]
 [2 4 7]]


In [3]:
import numpy as np

C_T = C.T  # memanggil matriks tranpose C

# perkalian matriks
kov = np.dot(C, C_T)
print(kov)


[[ 5 11 17]
 [11 25 39]
 [17 39 61]]


In [4]:
#matrix simetris
import numpy as np
s=np.array([[3,1,2],[1,6,0],[2,0,4]]) # ini adalah contoh matriks persegi
print("s=",s)


s_t=s.transpose()
print("s_t=",s_t)# hasil dari transpose matriks persegi sama dengan matriks aslinya

s= [[3 1 2]
 [1 6 0]
 [2 0 4]]
s_t= [[3 1 2]
 [1 6 0]
 [2 0 4]]


In [7]:
At=A.transpose() #(At)t=A
print("At=",At)
Att=At.transpose()
print("Att=",Att)
#dari contoh ini membuktikan bahwa A transpose jika di transpose kembali maka hasilnya adalah matriks A

At= [[1 3 9]
 [2 4 7]
 [3 5 6]]
Att= [[1 2 3]
 [3 4 5]
 [9 7 6]]


In [12]:
#(A+B)t=At+Bt
# hitung matrik A + B
AB=A+B

# Hitung transpose dari penjumlahan matriks A dan B
ABt=AB.transpose()
print("Hasil penjumlahan matriks A dan B:")
print(AB)
print("\nTransposenya:")
print(ABt)
print("=====================")


At=A.transpose()
print("At=")
print(At)
Bt=B.transpose()
print("Bt=")
print(Bt)
jl=At+Bt
print("jumlah At+Bt=")
print(jl)


Hasil penjumlahan matriks A dan B:
[[ 5  4  7]
 [ 6 11 10]
 [18 14 13]]

Transposenya:
[[ 5  6 18]
 [ 4 11 14]
 [ 7 10 13]]
At=
[[1 3 9]
 [2 4 7]
 [3 5 6]]
Bt=
[[4 3 9]
 [2 7 7]
 [4 5 7]]
jumlah At+Bt=
[[ 5  6 18]
 [ 4 11 14]
 [ 7 10 13]]
