 # PageRank
 -------------------------

 Algoritma pagerank pertama kali diperkenalkan oleh lary page.biasanya digunakan untuk menetukan peringkat halaman web dimesin pencarian google,dan menentukan peringkat pengguna di media sosial . sehingga dengan algoritma pagerank kita mampu memperkirakan seberapa bagus suatu situs web.


 ## Cara Kerja PageRank untuk menghitung nilai web:
 -------------------------

1. **Jumlah Tautan**: Semakin banyak tautan yang mengarah ke suatu halaman, semakin penting halaman tersebut.
2. **Kualitas Tautan**: Tautan dari halaman dengan PageRank tinggi memiliki bobot yang lebih tinggi dibandingkan tautan dari halaman dengan PageRank rendah.
3. **Konektivitas Link**: Distribusi link dan konektivitasnya di setiap situs web juga mempengaruhi PageRank.


PageRank bekerja dengan menghitung jumlah dan kualitas tautan ke suatu halaman untuk menentukan perkiraan kasar seberapa penting situs web tersebut. Algoritma ini memberikan nilai mulai dari 0 hingga 10 untuk menunjukkan seberapa berkualitasnya website tersebut. Semakin tinggi nilai PageRank, semakin kredibel website tersebut dianggap.

### Faktor Penentu PageRank
-------------------------

Beberapa faktor yang mempengaruhi PageRank adalah:

1. **Backlinks**: Jumlah dan kualitas tautan masuk yang mengarah ke suatu halaman.
2. **Internal Linking**: Tautan internal yang mengarah ke halaman lain di dalam situs web.
3. **External Linking**: Tautan eksternal yang mengarah ke situs web lain.



### Status PageRank Saat Ini
-------------------------

Walaupun PageRank tidak lagi ditampilkan secara publik, algoritma ini masih digunakan dalam sistem internal Google. Namun, penting untuk diingat bahwa PageRank bukanlah satu-satunya faktor yang menentukan ranking halaman di hasil pencarian Google. Ada banyak faktor lain yang juga berperan, seperti konten halaman, kegunaan, kecepatan loading, dan lain-lain.



Rumus PageRank yang asli dikembangkan oleh pendiri Google Lawrence Page dan Sergey Brin adalah sebagai berikut:
$
PR(A) = (1 - d) + d (PR(T1) / C(T1) + ... + PR(Tn) / C(Tn))
$
Di mana:

- PR(A) adalah PageRank halaman A
- PR(Ti) adalah PageRank halaman Ti yang menautkan ke halaman A
- C(Ti) adalah jumlah tautan eksternal halaman Ti
- d adalah koefisien dump yang berkisar dari 0 hingga 1, biasanya nilai acak adalah 0,85[3].


contoh perhitungan manual matriks A dan vektor v()


$A = \begin{pmatrix}
0 & 0 & 1 & \frac{1}{2} \\
\frac{1}{3} & 0 & 0 & 0 \\
\frac{1}{3} & \frac{1}{2} & 0 & \frac{1}{2} \\
\frac{1}{3} & \frac{1}{2} & 0 & 0
\end{pmatrix}, \quad
v = \begin{pmatrix}
0.25 \\
0.25 \\
0.25 \\
0.25
\end{pmatrix}$

### iterasi 1
 (\(A $\times $v\))

$
A \times v = \begin{pmatrix}
0 & 0 & 1 & \frac{1}{2} \\
\frac{1}{3} & 0 & 0 & 0 \\
\frac{1}{3} & \frac{1}{2} & 0 & \frac{1}{2} \\
\frac{1}{3} & \frac{1}{2} & 0 & 0
\end{pmatrix}
\times
\begin{pmatrix}
0.25 \\
0.25 \\
0.25 \\
0.25
\end{pmatrix}$
=
$\begin{pmatrix}
0 \times 0.25 + 0 \times 0.25 + 1 \times 0.25 + \frac{1}{2} \times 0.25 \\
\frac{1}{3} \times 0.25 + 0 \times 0.25 + 0 \times 0.25 + 0 \times 0.25 \\
\frac{1}{3} \times 0.25 + \frac{1}{2} \times 0.25 + 0 \times 0.25 + \frac{1}{2} \times 0.25 \\
\frac{1}{3} \times 0.25 + \frac{1}{2} \times 0.25 + 0 \times 0.25 + 0 \times 0.25
\end{pmatrix}$
=
$\begin{pmatrix}
0.375 \\
0.0833 \\
0.2917 \\
0.2083
\end{pmatrix}
$



### iterasi ke 2
\(A^2 $ \times $ v = A $\times$ (A $\times$ v)\):

\[
A^2 $\times$ v = A $\times$
$\begin{pmatrix}
0.375 \\
0.0833 \\
0.3333 \\
0.2083
\end{pmatrix}$
=
$\begin{pmatrix}
0 & 0 & 1 & \frac{1}{2} \\
\frac{1}{3} & 0 & 0 & 0 \\
\frac{1}{3} & \frac{1}{2} & 0 & \frac{1}{2} \\
\frac{1}{3} & \frac{1}{2} & 0 & 0
\end{pmatrix}$
$\times$
$\begin{pmatrix}
0.375 \\
0.0833 \\
0.3333 \\
0.2083
\end{pmatrix}$
=
$\begin{pmatrix}
0 \times 0.375 + 0 \times 0.0833 + 1 \times 0.3333 + \frac{1}{2} \times 0.2083 \\
\frac{1}{3} \times 0.375 + 0 \times 0.0833 + 0 \times 0.3333 + 0 \times 0.2083 \\
\frac{1}{3} \times 0.375 + \frac{1}{2} \times 0.0833 + 0 \times 0.3333 + \frac{1}{2} \times 0.2083 \\
\frac{1}{3} \times 0.375 + \frac{1}{2} \times 0.0833 + 0 \times 0.3333 + 0 \times 0.2083
\end{pmatrix}$
=
$\begin{pmatrix}
0.3333 + 0.10415 \\
0.125 \\
0.125 + 0.04165 + 0.10415 \\
0.125 + 0.04165
\end{pmatrix}$
=
$\begin{pmatrix}
0.43745 \\
0.125 \\
0.2708 \\
0.16665
\end{pmatrix}$
\]




### iterasi ke 3

\($A^3 \times$ v = A $\times$ (A^2 $\times$ v)\):

\[$
A^3 \times v = A \times \begin{pmatrix}
0.43745 \\
0.125 \\
0.2708 \\
0.16665
\end{pmatrix}$
=
$\begin{pmatrix}
0 & 0 & 1 & \frac{1}{2} \\
\frac{1}{3} & 0 & 0 & 0 \\
\frac{1}{3} & \frac{1}{2} & 0 & \frac{1}{2} \\
\frac{1}{3} & \frac{1}{2} & 0 & 0
\end{pmatrix}
\times$
$\begin{pmatrix}
0.43745 \\
0.125 \\
0.2708 \\
0.16665
\end{pmatrix}$
=
$\begin{pmatrix}
0 \times 0.43745 + 0 \times 0.125 + 1 \times 0.2708 + \frac{1}{2} \times 0.16665 \\
\frac{1}{3} \times 0.43745 + 0 \times 0.125 + 0 \times 0.2708 + 0 \times 0.16665 \\
\frac{1}{3} \times 0.43745 + \frac{1}{2} \times 0.125 + 0 \times 0.2708 + \frac{1}{2} \times 0.16665 \\
\frac{1}{3} \times 0.43745 + \frac{1}{2} \times 0.125 + 0 \times 0.2708 + 0 \times 0.16665
\end{pmatrix}$
\]

penyederhanaan:

\[
=
$\begin{pmatrix}
0.2708 + 0.083325 \\
0.1458167 \\
0.1458167 + 0.0625 + 0.083325 \\
0.1458167 + 0.0625
\end{pmatrix}$
=
$\begin{pmatrix}
0.354125 \\
0.1458167 \\
0.2916417 \\
0.2083167
\end{pmatrix}$
\]

jadi ,hasil dari \(A^3 $\times$ v\) :

\[
$A^3 \times v = \begin{pmatrix}
0.354125 \\
0.1458167 \\
0.2916417 \\
0.2083167
\end{pmatrix}$
\]





### iterasi ke 4
 \($A^4$ $\times$ v = A $\times$ ($A^3$ $\times$ v)\):

\[
$A^4 \times v = A \times \begin{pmatrix}
0.354125 \\
0.1458167 \\
0.2916417 \\
0.2083167
\end{pmatrix}$
=
$\begin{pmatrix}
0 & 0 & 1 & \frac{1}{2} \\
\frac{1}{3} & 0 & 0 & 0 \\
\frac{1}{3} & \frac{1}{2} & 0 & \frac{1}{2} \\
\frac{1}{3} & \frac{1}{2} & 0 & 0
\end{pmatrix}
\times$
$\begin{pmatrix}
0.354125 \\
0.1458167 \\
0.2916417 \\
0.2083167
\end{pmatrix}$
\]

Perhitungan:

\[
=
$\begin{pmatrix}
0 \times 0.354125 + 0 \times 0.1458167 + 1 \times 0.2916417 + \frac{1}{2} \times 0.2083167 \\
\frac{1}{3} \times 0.354125 + 0 \times 0.1458167 + 0 \times 0.2916417 + 0 \times 0.2083167 \\
\frac{1}{3} \times 0.354125 + \frac{1}{2} \times 0.1458167 + 0 \times 0.2916417 + \frac{1}{2} \times 0.2083167 \\
\frac{1}{3} \times 0.354125 + \frac{1}{2} \times 0.1458167 + 0 \times 0.2916417 + 0 \times 0.2083167
\end{pmatrix}$
\]

penyederhanaan :

\[
=
$\begin{pmatrix}
0.2916417 + 0.10415835 \\
0.11804167 \\
0.11804167 + 0.07290835 + 0.10415835 \\
0.11804167 + 0.07290835
\end{pmatrix}$
=
$\begin{pmatrix}
0.3958 \\
0.11804167 \\
0.29510837 \\
0.19095
\end{pmatrix}$
\]

jadi,hasil perhitungan \(A^4 $\times$ v\):

\[
$A^4 \times v = \begin{pmatrix}
0.3958 \\
0.11804167 \\
0.29510837 \\
0.19095
\end{pmatrix}$
\]



### iterasi ke 5
\($A^5 \times$ v = A $\times $($A^4$ $\times$ v)\):

\[
$A^5 \times v = A \times \begin{pmatrix}
0.3958 \\
0.11804167 \\
0.29510837 \\
0.19095
\end{pmatrix}$
=
$\begin{pmatrix}
0 & 0 & 1 & \frac{1}{2} \\
\frac{1}{3} & 0 & 0 & 0 \\
\frac{1}{3} & \frac{1}{2} & 0 & \frac{1}{2} \\
\frac{1}{3} & \frac{1}{2} & 0 & 0
\end{pmatrix}
\times$
$\begin{pmatrix}
0.3958 \\
0.11804167 \\
0.29510837 \\
0.19095
\end{pmatrix}$
\]

perhitungan:

\[
=
$\begin{pmatrix}
0 \times 0.3958 + 0 \times 0.11804167 + 1 \times 0.29510837 + \frac{1}{2} \times 0.19095 \\
\frac{1}{3} \times 0.3958 + 0 \times 0.11804167 + 0 \times 0.29510837 + 0 \times 0.19095 \\
\frac{1}{3} \times 0.3958 + \frac{1}{2} \times 0.11804167 + 0 \times 0.29510837 + \frac{1}{2} \times 0.19095 \\
\frac{1}{3} \times 0.3958 + \frac{1}{2} \times 0.11804167 + 0 \times 0.29510837 + 0 \times 0.19095
\end{pmatrix}$
\]

perhitungan:

\[
=
$\begin{pmatrix}
0.29510837 + 0.095475 \\
0.13193333 \\
0.13193333 + 0.059020835 + 0.095475 \\
0.13193333 + 0.059020835
\end{pmatrix}$
=
$\begin{pmatrix}
0.39058337 \\
0.13193333 \\
0.286429165 \\
0.190954165
\end{pmatrix}$
\]

jadi,hasil dari  \(A^5 $\times$ v\) is:

\[
$A^5 \times v = \begin{pmatrix}
0.39058337 \\
0.13193333 \\
0.286429165 \\
0.190954165
\end{pmatrix}$
\]




### iterasi ke 6
\($A^6$ $\times$ v = A $\times$ ($A^5$ $\times$ v)\):

\[
$A^6 \times v = A \times \begin{pmatrix}
0.39058337 \\
0.13193333 \\
0.286429165 \\
0.190954165
\end{pmatrix}$
=
$\begin{pmatrix}
0 & 0 & 1 & \frac{1}{2} \\
\frac{1}{3} & 0 & 0 & 0 \\
\frac{1}{3} & \frac{1}{2} & 0 & \frac{1}{2} \\
\frac{1}{3} & \frac{1}{2} & 0 & 0
\end{pmatrix}
\times$
$\begin{pmatrix}
0.39058337 \\
0.13193333 \\
0.286429165 \\
0.190954165
\end{pmatrix}$
\]

perhitungan:

\[
=
$\begin{pmatrix}
0 \times 0.39058337 + 0 \times 0.13193333 + 1 \times 0.286429165 + \frac{1}{2} \times 0.190954165 \\
\frac{1}{3} \times 0.39058337 + 0 \times 0.13193333 + 0 \times 0.286429165 + 0 \times 0.190954165 \\
\frac{1}{3} \times 0.39058337 + \frac{1}{2} \times 0.13193333 + 0 \times 0.286429165 + \frac{1}{2} \times 0.190954165 \\
\frac{1}{3} \times 0.39058337 + \frac{1}{2} \times 0.13193333 + 0 \times 0.286429165 + 0 \times 0.190954165
\end{pmatrix}$
\]
penyederhanaan:

\[
=
$\begin{pmatrix}
0.286429165 + 0.0954770825 \\
0.1301944567 \\
0.1301944567 + 0.065966665 + 0.0954770825 \\
0.1301944567 + 0.065966665
\end{pmatrix}$
=
$\begin{pmatrix}
0.3819062475 \\
0.1301944567 \\
0.2916382042 \\
0.1961611217
\end{pmatrix}$
\]

jadi,hasil dari \$(A^6 \times v\)$ :

\[
$A^6 \times v = \begin{pmatrix}
0.3819062475 \\
0.1301944567 \\
0.2916382042 \\
0.1961611217
\end{pmatrix}$
\]




### iterasi ke 7
\($A^7$ $\times$ v = A $\times$ ($A^6$ $\times$ v)\):

\[
$A^7 \times v = A \times \begin{pmatrix}
0.3819062475 \\
0.1301944567 \\
0.2916382042 \\
0.1961611217
\end{pmatrix}$
=
$\begin{pmatrix}
0 & 0 & 1 & \frac{1}{2} \\
\frac{1}{3} & 0 & 0 & 0 \\
\frac{1}{3} & \frac{1}{2} & 0 & \frac{1}{2} \\
\frac{1}{3} & \frac{1}{2} & 0 & 0
\end{pmatrix}
\times$
$\begin{pmatrix}
0.3819062475 \\
0.1301944567 \\
0.2916382042 \\
0.1961611217
\end{pmatrix}$
\]

perhitungan:

\[
=
$\begin{pmatrix}
0 \times 0.3819062475 + 0 \times 0.1301944567 + 1 \times 0.2916382042 + \frac{1}{2} \times 0.1961611217 \\
\frac{1}{3} \times 0.3819062475 + 0 \times 0.1301944567 + 0 \times 0.2916382042 + 0 \times 0.1961611217 \\
\frac{1}{3} \times 0.3819062475 + \frac{1}{2} \times 0.1301944567 + 0 \times 0.2916382042 + \frac{1}{2} \times 0.1961611217 \\
\frac{1}{3} \times 0.3819062475 + \frac{1}{2} \times 0.1301944567 + 0 \times 0.2916382042 + 0 \times 0.1961611217
\end{pmatrix}$
\]

penyederhanaan:

\[
=
$\begin{pmatrix}
0.2916382042 + 0.09808056085 \\
0.1273020825 \\
0.1273020825 + 0.06509722835 + 0.09808056085 \\
0.1273020825 + 0.06509722835
\end{pmatrix}$
=
$\begin{pmatrix}
0.38971876505 \\
0.1273020825 \\
0.2904798717 \\
0.19239931085
\end{pmatrix}$
\]

jadi, hasil dari \$(A^7 \times$ v\) is:

\[
$A^7 \times v = \begin{pmatrix}
0.38971876505 \\
0.1273020825 \\
0.2904798717 \\
0.19239931085
\end{pmatrix}$
\]




### iterasi ke 8
\($A^8 $$\times$ v = A $ \times$ ($A^7$ $\times$ v)\):

\[
$A^8 \times v = A \times \begin{pmatrix}
0.38971876505 \\
0.1273020825 \\
0.2904798717 \\
0.19239931085
\end{pmatrix}$
=
$\begin{pmatrix}
0 & 0 & 1 & \frac{1}{2} \\
\frac{1}{3} & 0 & 0 & 0 \\
\frac{1}{3} & \frac{1}{2} & 0 & \frac{1}{2} \\
\frac{1}{3} & \frac{1}{2} & 0 & 0
\end{pmatrix}
\times$
$\begin{pmatrix}
0.38971876505 \\
0.1273020825 \\
0.2904798717 \\
0.19239931085
\end{pmatrix}$
\]

perhitungan:

\[
=
$\begin{pmatrix}
0 \times 0.38971876505 + 0 \times 0.1273020825 + 1 \times 0.2904798717 + \frac{1}{2} \times 0.19239931085 \\
\frac{1}{3} \times 0.38971876505 + 0 \times 0.1273020825 + 0 \times 0.2904798717 + 0 \times 0.19239931085 \\
\frac{1}{3} \times 0.38971876505 + \frac{1}{2} \times 0.1273020825 + 0 \times 0.2904798717 + \frac{1}{2} \times 0.19239931085 \\
\frac{1}{3} \times 0.38971876505 + \frac{1}{2} \times 0.1273020825 + 0 \times 0.2904798717 + 0 \times 0.19239931085
\end{pmatrix}$
\]

penyederhanaan:

\[
=
$\begin{pmatrix}
0.2904798717 + 0.096199655425 \\
0.12990625501666667 \\
0.12990625501666667+ 0.06365104125 + 0.096199655425 \\
0.12990625501666667 +0.06365104125
\end{pmatrix}$
=
$\begin{pmatrix}
0.386679527125 \\
0.12990625501666667 \\
0.2897569516916667 \\
0.19355729626666668
\end{pmatrix}$
\]

jadi, hasil dari \$(A^8 \times$ v\) is:

\[
$A^8 \times v = \begin{pmatrix}
0.38971876505 \\
0.1299062550166666 \\
0.2897569516916667 \\
0.19355729626666668
\end{pmatrix}$
\]



In [ ]:
import numpy as np

A = np.array([[0,0,1,1/2], [1/3, 0 ,0 ,0], [1/3,1/2,0,1/2],[1/3,1/2,0,0]])
v = np.array([[0.25], [0.25], [0.25], [0.25]])

print ('A x v=\n', np.dot(A, v))z
print ('A^2 x v=\n', np.dot(A, np.dot(A, v)))
print ('A x (Av)=\n', np.dot(A, np.dot(A, v)))
print ('A^3 x v=\n', np.dot(A, np.dot(A, np.dot(A, v))))
print ('A^4 x v=\n', np.dot(A, np.dot(A, np.dot(A, np.dot(A, v)))))
print ('A^5 x v=\n', np.dot(A, np.dot(A, np.dot(A, np.dot(A, np.dot(A, v))))))
print ('A^6 x v=\n', np.dot(A, np.dot(A, np.dot(A, np.dot(A, np.dot(A, np.dot(A, v)))))))
print ('A^7 x v=\n', np.dot(A, np.dot(A, np.dot(A, np.dot(A, np.dot(A, np.dot(A, np.dot(A, v))))))))
print ('A^8 x v=\n', np.dot(A, np.dot(A, np.dot(A, np.dot(A, np.dot(A, np.dot(A, np.dot(A, np.dot(A, v)))))))))

A x v=
 [[0.375     ]
 [0.08333333]
 [0.33333333]
 [0.20833333]]
A^2 x v=
 [[0.4375    ]
 [0.125     ]
 [0.27083333]
 [0.16666667]]
A x (Av)=
 [[0.4375    ]
 [0.125     ]
 [0.27083333]
 [0.16666667]]
A^3 x v=
 [[0.35416667]
 [0.14583333]
 [0.29166667]
 [0.20833333]]
A^4 x v=
 [[0.39583333]
 [0.11805556]
 [0.29513889]
 [0.19097222]]
A^5 x v=
 [[0.390625  ]
 [0.13194444]
 [0.28645833]
 [0.19097222]]
A^6 x v=
 [[0.38194444]
 [0.13020833]
 [0.29166667]
 [0.19618056]]
A^7 x v=
 [[0.38975694]
 [0.12731481]
 [0.29050926]
 [0.19241898]]
A^8 x v=
 [[0.38671875]
 [0.12991898]
 [0.28978588]
 [0.19357639]]


In [ ]:
import numpy as np

A = np.array([[0, 0, 1, 1/2],
              [1/3, 0, 0, 0],
              [1/3, 1/2, 0, 1/2],
              [1/3, 1/2, 0, 0]])

v = np.array([[0.25], [0.25], [0.25], [0.25]])
#v = np.array([[0.20], [0.30], [0.20], [0.30]])

previous_result = v
tolerance = 0.01  # Ubah nilai toleransi menjadi 0.01

for i in range(1, 100):  # Batasi jumlah iterasi untuk mencegah perulangan tak terbatas
    result = A @ previous_result
    print(f"(A^{i})v = \n", result)

    # Cek kondisi berhenti
    if np.all(np.abs(result - previous_result) <= tolerance):
        if np.sqrt(np.sum((result - previous_result) ** 2)) < tolerance:
          print(f"\nPerkalian matriks konvergen pada iterasi ke-{i}.")
          break

    previous_result = result

(A^1)v = 
 [[0.375     ]
 [0.08333333]
 [0.33333333]
 [0.20833333]]
(A^2)v = 
 [[0.4375    ]
 [0.125     ]
 [0.27083333]
 [0.16666667]]
(A^3)v = 
 [[0.35416667]
 [0.14583333]
 [0.29166667]
 [0.20833333]]
(A^4)v = 
 [[0.39583333]
 [0.11805556]
 [0.29513889]
 [0.19097222]]
(A^5)v = 
 [[0.390625  ]
 [0.13194444]
 [0.28645833]
 [0.19097222]]
(A^6)v = 
 [[0.38194444]
 [0.13020833]
 [0.29166667]
 [0.19618056]]
(A^7)v = 
 [[0.38975694]
 [0.12731481]
 [0.29050926]
 [0.19241898]]

Perkalian matriks konvergen pada iterasi ke-7.
