# DETERMINAN

### contoh fungsi untuk menghitung determinan dalam python



In [ ]:
import numpy as np
A = np.array([[6,2],[4,2]])
B = np.array([[3,7],[4,8]])
C = np.array([[1,0],[0,1]])
D = np.array([[1,0,0],[0,1,0],[0,0,1]])
F = np.array([[1,4,2],[1,1,1],[3,2,1]])



det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_C = np.linalg.det(C)
det_D = np.linalg.det(D)
det_F = np.linalg.det(F)




print("Matriks 2x2")
print(f"matrik A:\n {A}")
print(f"Determinan Matrix A :\n{det_A}")
print("")
print(f"matrik B:\n{B}")
print(f"Determinan Matrix B :\n{det_B}")
print("")
print(f"matrik C:\n{C}")
print(f"Determinan Matrix C :\n{det_C}")
print("")
print("Matriks 3x3  ")
print(f"matrik D:\n{D}")
print(f"Determinan Matrix D :\n{det_D}")
print("")
print(f"matrik F:\n{F}")
print(f"Determinan Matrix F :\n{det_F}")
print("")


inv_A = np.linalg.inv(A)
inv_B = np.linalg.inv(B)
print(f"invers Matrix A :\n{inv_A}")
print(f"invers Matrix B :\n{inv_B}")


Matriks 2x2
matrik A:
 [[6 2]
 [4 2]]
Determinan Matrix A :
4.000000000000001

matrik B:
[[3 7]
 [4 8]]
Determinan Matrix B :
-4.0

matrik C:
[[1 0]
 [0 1]]
Determinan Matrix C :
1.0

Matriks 3x3  
matrik D:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Determinan Matrix D :
1.0

matrik F:
[[1 4 2]
 [1 1 1]
 [3 2 1]]
Determinan Matrix F :
5.000000000000001

invers Matrix A :
[[ 0.5 -0.5]
 [-1.   1.5]]
invers Matrix B :
[[-2.    1.75]
 [ 1.   -0.75]]


# Sifat-Sifat Derterminan Matriks
1.Derterminan matriks identitas dengan ordo berapapun adalah 1.

contoh berikut ini:




In [ ]:
import numpy as np
C = np.array([[1,0],[0,1]])
D = np.array([[1,0,0],[0,1,0],[0,0,1]])

det_C = np.linalg.det(C)
det_D = np.linalg.det(D)

print("Matriks 2x2  ")
print(f"matrik C:\n{C}")
print(f"Determinan Matrix C :\n{det_C}")
print("")
print("Matriks 3x3  ")
print(f"matrik D:\n{D}")
print(f"Determinan Matrix D :\n{det_D}")
print("")


Matriks 2x2  
matrik C:
[[1 0]
 [0 1]]
Determinan Matrix C :
1.0

Matriks 3x3  
matrik D:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Determinan Matrix D :
1.0



# Sifat-Sifat Derterminan Matriks
2.jika salah satu baris diubah nilai elemenya maka hasil determinannya juga ikut berubah.

contoh berikut ini:




In [ ]:
G = np.array([[2,2,3],[1,3,1],[2,4,2]])

det_G= np.linalg.det(G)
print(f"matrik G:\n{G}")
print(f"Determinan Matrix G :\n{det_G}")

matrik G:
[[2 2 3]
 [1 3 1]
 [2 4 2]]
Determinan Matrix G :
-2.0


In [ ]:
G1 = np.array([[2,4,2],[1,3,1],[2,2,3]])

det_G1= np.linalg.det(G1)
print(f"matrik G:\n{G1}")
print(f"Determinan Matrix G :\n{det_G1}")

matrik G:
[[2 4 2]
 [1 3 1]
 [2 2 3]]
Determinan Matrix G :
2.0


# Sifat-Sifat Derterminan Matriks
3.jika suatu baris / kolom merupakan kelipatan dari baris yang lain maka determinan matriks tersebut adalah 0(baris 2 adalah kelipatan dari baris 1)

contoh berikut ini:




In [ ]:
H = np.array([[2,4,2],[1,6,1],[4,8,4]])

det_H= np.linalg.det(H)
print(f"matrik H:\n{H}")
print(f"Determinan Matrix G :\n{det_H}")

matrik H:
[[2 4 2]
 [1 6 1]
 [4 8 4]]
Determinan Matrix G :
0.0


contoh lain misal kolom 1 kelipatan dari kolom 3

In [ ]:
H1 = np.array([[4,4,2],[2,6,1],[8,8,4]])

det_H1= np.linalg.det(H1)
print(f"matrik H1:\n{H1}")
print(f"Determinan Matrix h1 :\n{det_H1}")

matrik H1:
[[4 4 2]
 [2 6 1]
 [8 8 4]]
Determinan Matrix h1 :
0.0


# Sifat-Sifat Derterminan Matriks
4.jika matriks adalah kelipatan sebanyak n * matrix maka untuk mencari determinan adalah (n^(sebanyak ordo)determinan matrix)contoh matrix i adalah kelipatan 2 kali dari matrix G : (2^3(det G))



In [ ]:
import numpy as np

i = np.array([[4, 4, 6], [2, 6, 2], [4, 8, 4]])
det_i = np.linalg.det(i)
rounded_det_i = round(det_i)

print(f"Matriks i:\n{i}")
print(f"Determinan Matriks i:\n{rounded_det_i}")


Matriks i:
[[4 4 6]
 [2 6 2]
 [4 8 4]]
Determinan Matriks i:
-16.0


# Sifat-Sifat Derterminan Matriks
5.jika terdapat matrix baru dengan nilai salah satu baris atau kolom adalah kelipatan 2 dari matrix sebelumnya maka dapat disimpulkan dengan 2*(determinan matrix)




In [ ]:

import numpy as np
j = np.array([[3,5],[2,4]])

det_j= np.linalg.det(j)
print(f"matrik j:\n{j}")
print(f"Determinan Matrix j :\n{det_j}")

matrik j:
[[3 5]
 [2 4]]
Determinan Matrix j :
2.000000000000001


In [ ]:
# contoh matriks j1 baris pertama merupakan kelipatan 2 dari matriks j
import numpy as np
j1 = np.array([[6,10],[2,4]])

det_j1= np.linalg.det(j1)
print(f"matrik j1:\n{j1}")
print(f"Determinan Matrix j1 :\n{det_j1}")

matrik j1:
[[ 6 10]
 [ 2  4]]
Determinan Matrix j1 :
4.000000000000002


In [ ]:
# contoh matriks j2 kolom pertama merupakan kelipatan 2 dari matriks j
import numpy as np
j2 = np.array([[6,5],[4,4]])

det_j2= np.linalg.det(j2)
print(f"matrik j2:\n{j2}")
print(f"Determinan Matrix j2 :\n{det_j2}")

matrik j2:
[[6 5]
 [4 4]]
Determinan Matrix j2 :
4.000000000000002


# Sifat-Sifat Derterminan Matriks
6.Jika suatu matrix yang berasal dari penjumlahan matrix k dengan matrix a maka untuk mencari determinan cukup menjumlahkan hasil dari 2 determinan matrix tersebut


In [ ]:

import numpy as np
j = np.array([[3,5],[2,4]])

det_j= np.linalg.det(j)
print(f"matrik j:\n{j}")
print(f"Determinan Matrix j :\n{det_j}")

matrik j:
[[3 5]
 [2 4]]
Determinan Matrix j :
2.000000000000001


In [ ]:
import numpy as np
k = np.array([[3,3],[2,4]])

det_k= np.linalg.det(k)
print(f"matrik k:\n{k}")
print(f"Determinan Matrix k :\n{det_k}")

matrik k:
[[3 3]
 [2 4]]
Determinan Matrix k :
6.0


In [ ]:

import numpy as np
jk = np.array([[6,8],[2,4]])

det_jk= np.linalg.det(jk)
rounded_det_jk = round(det_jk)
print(f"matrik j:\n{jk}")
print("determinan matrik j:",det_j)
print("determinan matrik k:",det_k)
print(" determinan matrik jk = determinan j(2) + determinan k(6)")
print(f"Determinan Matrix jk :{rounded_det_jk}")

matrik j:
[[6 8]
 [2 4]]
determinan matrik j: 2.000000000000001
determinan matrik k: 6.0
 determinan matrik jk = determinan j(2) + determinan k(6)
Determinan Matrix jk :8


### Sifat 7 : Jika ada matrix segitiga atas atau bawah maka determinannya ialah perkalian anggota diagonal matrix tersebut.

In [ ]:
# 3x5x4=60
l = np.array([[3,4,2],[0,5,1],[0,0,4]])

det_l= np.linalg.det(l)
round_detl=round(det_l)
print(f"matrik l:\n{l}")
print(f"Determinan Matrix l :\n{round_detl}")

matrik l:
[[3 4 2]
 [0 5 1]
 [0 0 4]]
Determinan Matrix l :
60


In [ ]:
# 4x7x1=28
m = np.array([[4,0,0],[3,7,0],[5,6,1]])

det_m= np.linalg.det(m)
round_detm=round(det_m)
print(f"matrik m:\n{m}")
print(f"Determinan Matrix m :\n{round_detm}")

matrik m:
[[4 0 0]
 [3 7 0]
 [5 6 1]]
Determinan Matrix m :
28


### Sifat 8 : untuk mencari determinan dari Hasil perkalian matrix N dengan matrix O adalah dengan mengalikan determinan matrix N dan O contoh (det N = 10  , det O = 3 , maka det P adalah 30 )

In [ ]:
import numpy as np
N = np.array([[4,3],[2,4]])

det_N= np.linalg.det(N)
round_detN=round(det_N)
print(f"matrik N:\n{N}")
print(f"Determinan Matrix N :\n{round_detN}")

matrik N:
[[4 3]
 [2 4]]
Determinan Matrix N :
10


In [ ]:
import numpy as np
O = np.array([[5 ,2],[1,1]])

det_O= np.linalg.det(O)
round_detO=round(det_O)
print(f"matrik O:\n{O}")
print(f"Determinan Matrix O :\n{round_detO }")

matrik O:
[[5 2]
 [1 1]]
Determinan Matrix O :
3


In [ ]:
P=np.dot(N,O)
print(P)
det_P=np.linalg.det(P)
round_detP=round(det_P)
print(round_detP)

[[23 11]
 [14  8]]
30


# DETERMINAN MATRIKS DENGAN KOFAKTOR

$Q=\begin{bmatrix}
4 & 3 & 1 & 6\\
2 & 3 & 2 & 1\\
3 & 2 & 1 & 1\\
2 & 5 & 1 & 4
\end{bmatrix} Rumus-determinan= A11 × K11 + A12 × K12 + A13 × K13 + A14 × K14 $

### dari matriks buat kofaktor terlebih dahulu
 $ Kij= (-1)^i+j | Mij | $
 * arti dari rumus diatas adalah baris ke i dan kolom ke j dari matriks akan dihilangkan


$Q=+4\begin{bmatrix}
3 & 2 & 1 \\
2 & 1 & 1 \\
5 & 1 & 4
\end{bmatrix} $
$-3\begin{bmatrix}
2 & 2 & 1 \\
3 & 1 & 1 \\
2 & 1 & 4
\end{bmatrix} $
$+1\begin{bmatrix}
2 & 3 & 1 \\
3 & 2 & 1 \\
2 & 5 & 4
\end{bmatrix} $
$-6\begin{bmatrix}
2 & 3 & 2 \\
3 & 2 & 1 \\
2 & 5 & 1
\end{bmatrix} $

#### mencari kofaktor 11
$\begin{bmatrix}
3 & 2 & 1 \\
2 & 1 & 1 \\
5 & 1 & 4
\end{bmatrix} $
$+3\begin{bmatrix}
 1 & 1 \\
 1 & 4
\end{bmatrix} $
$-2\begin{bmatrix}
 2 & 1 \\
 5 & 4
\end{bmatrix} $
$+1\begin{bmatrix}
 2 & 1 \\
 5 & 1
\end{bmatrix} $


$ Rumus-determinan= A11 × K11 + A12 × K12 + A13 × K13 + A14 × K14 $
$ maka = +3 (1 × 4 - 1 × 1)+ (-2) (2 × 4 - 1 × 5)+ 1 (2 × 1 - 1 × 5) $
$ = +3(3) + (-2)(3) + 1(-3) $
$ = 9 + (-6) + (-3) $
$ =0 $
  

#### mencari kofaktor 12
$\begin{bmatrix}
2 & 2 & 1 \\
3 & 1 & 1 \\
2 & 1 & 4
\end{bmatrix} $
$+2\begin{bmatrix}
 1 & 1 \\
 1 & 4
\end{bmatrix} $
$-2\begin{bmatrix}
 3 & 1 \\
 2 & 4
\end{bmatrix} $
$+1\begin{bmatrix}
 3 & 1 \\
 2 & 1
\end{bmatrix} $


$ Rumus-determinan= A11 × K11 + A12 × K12 + A13 × K13 + A14 × K14 $
$ maka = +2 (1 × 4 - 1 × 1)+ (-2) (3 × 4 - 1 × 2)+ 1 (3 × 1 - 1 × 2) $
$ = +2(3) + (-2)(10) + 1(1) $
$ = 6 + (-20) + (1) $
$ = -13 $
  

#### mencari kofaktor 13
$\begin{bmatrix}
2 & 3 & 1 \\
3 & 2 & 1 \\
2 & 5 & 4
\end{bmatrix} $
$+2\begin{bmatrix}
 2 & 1 \\
 5 & 4
\end{bmatrix} $
$-3\begin{bmatrix}
 3 & 1 \\
 2 & 4
\end{bmatrix} $
$+1\begin{bmatrix}
 3 & 2 \\
 2 & 5
\end{bmatrix} $


$ Rumus-determinan= A11 × K11 + A12 × K12 + A13 × K13 + A14 × K14 $
$ maka = +2 (2 × 4 - 1 × 5)+ (-3) (3 × 4 - 1 × 2)+ 1 (3 × 5 - 2 × 2) $
$ = +2(3) + (-3)(10) + 1(11) $
$ = 6 + (-30) + 11 $
$ = -13 $
  

#### mencari kofaktor 14
$\begin{bmatrix}
2 & 3 & 2 \\
3 & 2 & 1 \\
2 & 5 & 1
\end{bmatrix} $
$+2\begin{bmatrix}
 2 & 1 \\
 5 & 1
\end{bmatrix} $
$-3\begin{bmatrix}
 3 & 1 \\
 2 & 1
\end{bmatrix} $
$+2\begin{bmatrix}
 3 & 2 \\
 2 & 5
\end{bmatrix} $


$ Rumus-determinan= A11 × K11 + A12 × K12 + A13 × K13 + A14 × K14 $
$ maka = +2 (2 × 1 - 1 × 5)+ (-3) (3 × 1 - 1 × 2)+ 2 (3 × 5 - 2 × 2) $
$ = +2(-3) + (-3)(1) + 2(11) $
$ = (-6) + (-3) + 22 $
$ = 13 $
  

# hasil akhir
$Q=\begin{bmatrix}
4 & 3 & 1 & 6\\
2 & 3 & 2 & 1\\
3 & 2 & 1 & 1\\
2 & 5 & 1 & 4
\end{bmatrix} Rumus-determinan= A11 × K11 + A12 × K12 + A13 × K13 + A14 × K14 $

$ det Q = 4 × (0) + (-3) ×(-13) + 1 × (-13) + -(6) × (-13) $
$ = 0 + 39 + (-13) + (-78) $
$ = 39 + (-91)$
$ = - 52 $
