# Tugas 3
# Matrik Invers
#### Penjelasan
invers matriks adalah dua matriks persegi dengan ordo yang sama misal matriks A dan B disebut matriks invers jika memenuhi hubungan *AB=BA=I*
invers matriks

### Sifat-sifat Matriks
$1.AB=C => A=CB^{-1}$

$2.AB=C => B=A^{-1}C$

$3.AA^{-1}=A^{-1}A=1$

$4.(A^{-1})^{-1}=A$

$5.(AB^{-1})=B^{-1}.A^{-1}$



#### contoh ordo 2x2:

 $ A=\begin{pmatrix}
  3 & 5\\
  1 & 2
\end{pmatrix}$, dan

$B=\begin{pmatrix}
  2 & -5\\
  -1 & 3
\end{pmatrix}$,  

maka ,

$AB=\begin{pmatrix}
  3 & 5\\
  -1 & 2
\end{pmatrix}$
$\begin{pmatrix}
  2 & -5\\
  -1 & 3
\end{pmatrix}$=
$\begin{pmatrix}
  1& 0\\
  0 & 1
\end{pmatrix}$,


$BA=\begin{pmatrix}
  2 & 5\\
  -1 & 3
\end{pmatrix}$
$\begin{pmatrix}
  3 & 5\\
  1 & 2
\end{pmatrix}$=
$\begin{pmatrix}
  1& 0\\
  0 & 1
\end{pmatrix}$

Karena AB =BA=I maka A dan B adalah dua matriks yang saling invers


*Rumus Invers Matriks*

$A^{-1} = \frac{1}{\text{Det} A} \text{Adj}(A)$

misal $A=\begin{pmatrix}
  a& b\\
  c & d
\end{pmatrix}$
maka
$adj(A)=\begin{pmatrix}
  d& -b\\
  -c &
\end{pmatrix}$

**contoh**

jika
$A=\begin{pmatrix}
  3 & 5\\
  1 & 2
\end{pmatrix}$ maka $A^{-1}=$

$A^{-1} = \frac{1}{\text{6-5}} $
$A=\begin{pmatrix}
  2 & -5\\
  -1 & 3
\end{pmatrix}$

$= \frac{1}{\text{1}} $
$\begin{pmatrix}
  2 & -5\\
  -1 & 3
\end{pmatrix}$

$=\begin{pmatrix}
  2 & -5\\
  -1 & 3
\end{pmatrix}$


### contoh invers matrik ordo 3x3 :

$ B=\begin{bmatrix}
2 & 1 & 0\\
3 & -1 & 4\\
2 & 2 & 0
\end{bmatrix}$

maka,$B^{-1}=$

*penyelesaian:*

$B^{-1} = \frac{1}{\text{Det} B} \text{Adj}(B)$

Langkah pertama cari determinan B menggunakan metode rumus :

$ B=\begin{bmatrix}
2 & 1 & 0\\
3 & -1 & 4\\
2 & 2 & 0
\end{bmatrix}$
$\begin{vmatrix}
2 & 1\\
3 & -1\\
2 & 2\\
\end{vmatrix}$

Determinan B= (2x-1x0)+(1x4x2)+(0x3x2)-(0x-1x2)-(2x4x2)-(1x3x0)

Det B= 0+8+0-0-16-0= -8

Selanjutnya kita akan cari adjoin dengan an mencari minor terlebih dahulu

M11=((-1x0)-(4x2))=-8
M12=((3x0)-(4x2))=-8
M13=((3x2)-(-1x2))=8
M21=((1x0)-(2x0))=0
M22=((2x0)-(2x0))=0
M23=((2x2)-(1x2))=2
M31=((1x4)-(0x-1))=4
M32=((2x4)-(0x3))=8
M33=((2x-1)-(1x3))=-5

selanjutnya cari kofaktornya sebagai berikut:
$kof(B)=\begin{pmatrix}
+(-8) & -(-8) & +8\\
-0 & +0 & -2\\
+4 & -8 & +(-5)
\end{pmatrix}$
$=\begin{pmatrix}
-8 & 8 & 8\\
-0 & 0 & -2\\
4 & -8 & -5
\end{pmatrix}$

setelah itu mencari adjoin dengan yang didapat dari transpose kofaktor


${Adj}(B)=(kof(B))^{T}$


$Adj(B)=\begin{pmatrix}
-8 & 0 & 4\\
8 & 0 & -8\\
8 & -2 & -5
\end{pmatrix}$

Setelah itu mencari invers dengan rumusnya
$B^{-1} = \frac{1}{-8} \begin{pmatrix}
-8 & 0 & 4\\
8 & 0 & -8\\
8 & -2 & -5
\end{pmatrix}$
hasil akhir dari invers matriks B
$B^{-1} = \begin{pmatrix}
1 & 0 & -\frac{1}{2}\\
-1 & 0 & 1\\
-1 & \frac{1}{4} &  \frac{5}{8}
\end{pmatrix}$







# Berikut adalah invers Matriks dengan ordo 4x4 diselesaikan dengan metode gauss jordan :

Untuk mendapatkan invers matriks dengan metode gauss jordan maka, matriks A harus sandingkan dengan matriks identitas

$ A=\begin{bmatrix}
2 & 4 & 4 & 8\\
4 & 12 & 8 & 0\\
0 & 8 & 4 & 8\\
4 & 8 & 8 & 6\\
\end{bmatrix}$
$\begin{vmatrix}
1 & 0 & 0 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & 1 & 0\\
0 & 0 & 0 & 1\\
\end{vmatrix}$

In [ ]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.

#A: Matriks numpy yang akan dimodifikasi.
#k: Nomor baris yang akan diubah.
#scale: Skalar yang akan digunakan untuk mengalikan setiap elemen dalam baris ke-k.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.

#     A adalah matriks numpy yang akan dimodifikasi.
#k adalah nomor baris yang akan digunakan sebagai referensi.
#l adalah nomor baris yang akan dimodifikasi.
#scale adalah skalar yang akan digunakan untuk mengalikan baris ke-k sebelum ditambahkan ke baris ke-l.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [ ]:
import numpy as np
# Matriks A
A = np.array([[1, 2, 2, 4],[2, 6, 4, 0],[0, 4, 2, 4],[2, 4, 4, 3]])

# Matriks identitas
B  = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])

#I = np.identity(4)

print("Matriks A:")
print(A)
print("Matriks Identitas:")
print(B)


Matriks A:
[[1 2 2 4]
 [2 6 4 0]
 [0 4 2 4]
 [2 4 4 3]]
Matriks Identitas:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
A1 = RowAdd(A, 0,1 ,-2)
print(A1)
print("\n")

B1 = RowAdd(B, 0,1,-2)
print(B1)
print("\n")



[[ 1.  2.  2.  4.]
 [ 0.  2.  0. -8.]
 [ 0.  4.  2.  4.]
 [ 2.  4.  4.  3.]]


[[ 1.  0.  0.  0.]
 [-2.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]




In [ ]:
A2 = RowAdd(A1,0,3,-2)
print(A2)
print("\n")

B2 = RowAdd(B1,0,3,-2)
print(B2)
print("\n")

[[ 1.  2.  2.  4.]
 [ 0.  2.  0. -8.]
 [ 0.  4.  2.  4.]
 [ 0.  0.  0. -5.]]


[[ 1.  0.  0.  0.]
 [-2.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [-2.  0.  0.  1.]]




In [ ]:
A3=RowScale(A2,1,1/2)
print(A3)
print("\n")

B3 = RowScale(B2,1,1/2)
print(B3)
print("\n")

[[ 1.  2.  2.  4.]
 [ 0.  1.  0. -4.]
 [ 0.  4.  2.  4.]
 [ 0.  0.  0. -5.]]


[[ 1.   0.   0.   0. ]
 [-1.   0.5  0.   0. ]
 [ 0.   0.   1.   0. ]
 [-2.   0.   0.   1. ]]




In [ ]:
A4 = RowAdd(A3,1,2,-4)
print(A4)
print("\n")

B4 = RowAdd(B3,1,2,-4)
print(B4)
print("\n")

[[ 1.  2.  2.  4.]
 [ 0.  1.  0. -4.]
 [ 0.  0.  2. 20.]
 [ 0.  0.  0. -5.]]


[[ 1.   0.   0.   0. ]
 [-1.   0.5  0.   0. ]
 [ 4.  -2.   1.   0. ]
 [-2.   0.   0.   1. ]]




In [ ]:
A5=RowScale(A4,3,-1/5)
print(A5)
print("\n")

B5 = RowScale(B4,3,-1/5)
print(B5)
print("\n")

[[ 1.  2.  2.  4.]
 [ 0.  1.  0. -4.]
 [ 0.  0.  2. 20.]
 [-0. -0. -0.  1.]]


[[ 1.   0.   0.   0. ]
 [-1.   0.5  0.   0. ]
 [ 4.  -2.   1.   0. ]
 [ 0.4 -0.  -0.  -0.2]]




In [ ]:
A6 = RowAdd(A5,3,2,-20)
print(A6)
print("\n")

B6 = RowAdd(B5,3,2,-20)
print(B6)
print("\n")

[[ 1.  2.  2.  4.]
 [ 0.  1.  0. -4.]
 [ 0.  0.  2.  0.]
 [-0. -0. -0.  1.]]


[[ 1.   0.   0.   0. ]
 [-1.   0.5  0.   0. ]
 [-4.  -2.   1.   4. ]
 [ 0.4 -0.  -0.  -0.2]]




In [ ]:
A7 = RowAdd(A6,3,1,4)
print(A7)
print("\n")

B7 = RowAdd(B6,3,1,4)
print(B7)
print("\n")

[[ 1.  2.  2.  4.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  2.  0.]
 [-0. -0. -0.  1.]]


[[ 1.   0.   0.   0. ]
 [ 0.6  0.5  0.  -0.8]
 [-4.  -2.   1.   4. ]
 [ 0.4 -0.  -0.  -0.2]]




In [ ]:
A8 = RowAdd(A7,3,0,-4)
print(A8)
print("\n")

B8 = RowAdd(B7,3,0,-4)
print(B8)
print("\n")

[[ 1.  2.  2.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  2.  0.]
 [-0. -0. -0.  1.]]


[[-0.6  0.   0.   0.8]
 [ 0.6  0.5  0.  -0.8]
 [-4.  -2.   1.   4. ]
 [ 0.4 -0.  -0.  -0.2]]




In [ ]:
A9=RowScale(A8,2,1/2)
print(A9)
print("\n")

B9 = RowScale(B8,2,1/2)
print(B9)
print("\n")

[[ 1.  2.  2.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [-0. -0. -0.  1.]]


[[-0.6  0.   0.   0.8]
 [ 0.6  0.5  0.  -0.8]
 [-2.  -1.   0.5  2. ]
 [ 0.4 -0.  -0.  -0.2]]




In [ ]:
A10 = RowAdd(A9,2,0,-2)
print(A10)
print("\n")

B10 = RowAdd(B9,2,0,-2)
print(B10)
print("\n")

[[ 1.  2.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [-0. -0. -0.  1.]]


[[ 3.4  2.  -1.  -3.2]
 [ 0.6  0.5  0.  -0.8]
 [-2.  -1.   0.5  2. ]
 [ 0.4 -0.  -0.  -0.2]]




In [ ]:
A11 = RowAdd(A10,1,0,-2)
print(A11)
print("\n")

B11 = RowAdd(B10,1,0,-2)
print(B11)
print("\n")

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [-0. -0. -0.  1.]]


[[ 2.2  1.  -1.  -1.6]
 [ 0.6  0.5  0.  -0.8]
 [-2.  -1.   0.5  2. ]
 [ 0.4 -0.  -0.  -0.2]]


